#!/bin/bash
#
cd $HOME

# Configure Git
git config --global color.ui true
git config --global user.name "D4rkKnight21"
git config --global user.email "yusuff8621@gmail.com"

# Git Haxxx xD
echo "${git_cookies}" > ~/git_hax.sh
bash ~/git_hax.sh && rm ~/git_hax.sh

# Repo init  and sync
repo init -u https://github.com/CAF-Extended/manifest -b 11.0 --depth=1 --no-repo-verify -g default,-device,-mips,-darwin,-notdefault

# Start repo sync
repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

# Purge repo
rm -rf .repo

# Gapps
#rm -rf vendor/gms
#rm -rf device/generic/opengl-transport

# Pull Device Source
git clone https://github.com/D4rkKnight21/local_manifest --depth=1 -b cafex .repo/local_manifests